# Generated by Django 5.2.3 on 2025-06-10 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('ASA', 'ASA')], max_length=10, verbose_name='Materiale')),
                ('color_code', models.CharField(max_length=3, verbose_name='Codice Colore')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Codice Colore HEX')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Filamento',
                'verbose_name_plural': 'Filamenti',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Stampante')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modello')),
            ],
            options={
                'verbose_name': 'Stampante',
                'verbose_name_plural': 'Stampanti',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Piatto')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='app_3dmage_management.printer', verbose_name='Stampante')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Progetto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creato il')),
                ('priority', models.CharField(choices=[('URGENT', 'Urgente'), ('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Bassa')], default='MEDIUM', max_length=10, verbose_name='Priorità')),
                ('status', models.CharField(choices=[('QUOTE', 'Preventivo'), ('PREP', 'Da Preparare'), ('READY', 'Pronto da Stampare'), ('POST', 'Post-Produzione'), ('DONE', 'Completato')], default='QUOTE', max_length=10, verbose_name='Status')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità Oggetti')),
                ('notes', models.TextField(blank=True, verbose_name='Annotazioni')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_weight_g', models.PositiveIntegerField(default=1000, verbose_name='Peso Iniziale (g)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo (€)')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Acquisto')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spools', to='app_3dmage_management.filament', verbose_name='Filamento')),
            ],
            options={
                'verbose_name': 'Bobina',
                'verbose_name_plural': 'Bobine',
            },
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome G-Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Creazione')),
                ('print_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Tempo di Stampa (secondi)')),
                ('filament_used_g', models.PositiveIntegerField(default=0, verbose_name='Filamento Usato (g)')),
                ('status', models.CharField(choices=[('TODO', 'Da Stampare'), ('PRINTING', 'In Stampa'), ('DONE', 'Stampato'), ('FAILED', 'Fallito')], default='TODO', max_length=10, verbose_name='Status Stampa')),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.plate', verbose_name='Piatto Usato')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.printer', verbose_name='Stampante Usata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_files', to='app_3dmage_management.project', verbose_name='Progetto')),
                ('filament_spool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.spool', verbose_name='Bobina Filamento')),
            ],
            options={
                'verbose_name': 'File di Stampa',
                'verbose_name_plural': 'File di Stampa',
            },
        ),
    ]
