# Generated by Django 5.2.3 on 2025-06-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filament',
            options={'ordering': ['material', 'brand', 'color_code'], 'verbose_name': 'Filamento', 'verbose_name_plural': 'Filamenti'},
        ),
        migrations.AlterField(
            model_name='printfile',
            name='filament_spool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_files', to='app_3dmage_management.spool', verbose_name='Bobina Filamento'),
        ),
    ]
