# Generated by Django 5.2.3 on 2025-06-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0003_alter_printfile_options_printfile_queue_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Metodo')),
            ],
            options={
                'verbose_name': 'Metodo di Pagamento',
                'verbose_name_plural': 'Metodi di Pagamento',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Oggetto')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('status', models.CharField(choices=[('POST_PROD', 'Post-Produzione'), ('IN_STOCK', 'A Magazzino'), ('CONSIGNMENT', 'Conto Vendita'), ('SOLD', 'Venduto')], default='POST_PROD', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aggiunto il')),
                ('sold_at', models.DateField(blank=True, null=True, verbose_name='Data Vendita')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo di Vendita')),
                ('sold_to', models.CharField(blank=True, max_length=100, verbose_name='Venduto a (o rimborsato da)')),
                ('notes', models.TextField(blank=True, verbose_name='Note sulla vendita')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.paymentmethod', verbose_name='Metodo di Pagamento')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.project', verbose_name='Progetto Originale')),
            ],
            options={
                'verbose_name': 'Oggetto a Magazzino',
                'verbose_name_plural': 'Oggetti a Magazzino',
                'ordering': ['-created_at'],
            },
        ),
    ]
