# Generated by Django 5.2.3 on 2025-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0004_paymentmethod_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Completamento'),
        ),
    ]
