# Generated by Django 5.2.3 on 2025-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0005_project_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='bed_temp',
            field=models.PositiveIntegerField(default=60, verbose_name='Temperatura Piatto (°C)'),
        ),
        migrations.AddField(
            model_name='filament',
            name='nozzle_temp',
            field=models.PositiveIntegerField(default=215, verbose_name='Temperatura Ugello (°C)'),
        ),
        migrations.AddField(
            model_name='filament',
            name='volumetric_speed',
            field=models.PositiveIntegerField(default=15, verbose_name='Velocità Volumetrica (mm³/s)'),
        ),
    ]
