# Generated by Django 5.2.3 on 2025-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0006_filament_bed_temp_filament_nozzle_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filament',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome Colore'),
        ),
    ]
