# Generated by Django 5.2.3 on 2025-06-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0007_filament_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printfile',
            name='filament_spool',
        ),
        migrations.RemoveField(
            model_name='printfile',
            name='filament_used_g',
        ),
        migrations.CreateModel(
            name='FilamentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.PositiveIntegerField(default=0, verbose_name='Grammi Usati')),
                ('print_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_usages', to='app_3dmage_management.printfile')),
                ('spool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='app_3dmage_management.spool')),
            ],
        ),
        migrations.AddField(
            model_name='printfile',
            name='spools',
            field=models.ManyToManyField(related_name='print_files_usage', through='app_3dmage_management.FilamentUsage', to='app_3dmage_management.spool'),
        ),
    ]
