# Generated by Django 5.2.3 on 2025-06-12 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0008_remove_printfile_filament_spool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria Spesa')),
            ],
            options={
                'verbose_name': 'Categoria Spesa',
                'verbose_name_plural': 'Categorie Spesa',
            },
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Attuale'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo (€)')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Spesa')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.expensecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Spesa',
                'verbose_name_plural': 'Spese',
                'ordering': ['-expense_date'],
            },
        ),
    ]
