# Generated by Django 5.2.3 on 2025-06-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0009_expensecategory_paymentmethod_balance_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.paymentmethod', verbose_name='Pagato con'),
        ),
    ]
