# Generated by Django 5.2.3 on 2025-06-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0010_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Materiali'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sale_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commerciale'), ('PERSONAL', 'Personale')], default='COMMERCIAL', max_length=20, verbose_name='Tipo Vendita'),
        ),
    ]
