# Generated by Django 5.2.3 on 2025-06-12 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0011_stockitem_material_cost_stockitem_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Intervento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione Intervento')),
                ('notes', models.TextField(blank=True, verbose_name='Note Aggiuntive')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Ricambi (€)')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='app_3dmage_management.printer', verbose_name='Stampante')),
            ],
            options={
                'verbose_name': 'Log Manutenzione',
                'verbose_name_plural': 'Log Manutenzioni',
                'ordering': ['-log_date'],
            },
        ),
    ]
