# Generated by Django 5.2.3 on 2025-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0012_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chiave Impostazione')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valore')),
            ],
        ),
    ]
