# Generated by Django 5.2.3 on 2025-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0013_globalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Preventivo')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Totale')),
                ('details', models.JSONField(verbose_name='Dettagli Preventivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
