# Generated by Django 5.2.3 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0014_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Messaggio')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Successo'), ('WARNING', 'Attenzione'), ('DANGER', 'Pericolo')], default='INFO', max_length=10)),
                ('is_read', models.BooleanField(default=False, verbose_name='Letta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
