# Generated by Django 5.2.3 on 2025-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ID Personalizzato'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Personalizzato'),
        ),
    ]
