# Generated by Django 5.2.3 on 2025-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0016_project_custom_id_stockitem_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Link Acquisto'),
        ),
    ]
