# Generated by Django 5.2.3 on 2025-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0017_spool_purchase_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentusage',
            name='grams_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Grammi Usati'),
        ),
    ]
