# Generated by Django 5.2.3 on 2025-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0018_alter_filamentusage_grams_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ['purchase_date', 'identifier'], 'verbose_name': 'Bobina', 'verbose_name_plural': 'Bobine'},
        ),
        migrations.AddField(
            model_name='spool',
            name='identifier',
            field=models.CharField(blank=True, max_length=2, verbose_name='Identificatore'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('QUOTE', 'Preventivo'), ('TODO', 'Da Stampare'), ('POST', 'Post-Produzione'), ('DONE', 'Completato')], default='QUOTE', max_length=10, verbose_name='Status'),
        ),
    ]
