# Generated by Django 5.2.3 on 2025-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0020_populate_spool_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Oggetti Stampati Effettivi'),
        ),
        migrations.AddField(
            model_name='printfile',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Oggetti per Stampa'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Oggetti Stampati Effettivi'),
        ),
        migrations.AddField(
            model_name='project',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Oggetti per Stampa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantità oggetti ordine'),
        ),
    ]
