# Generated by Django 5.2.3 on 2025-06-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0021_printfile_actual_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prezzo di Vendita Previsto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
