# Generated by Django 5.2.3 on 2025-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0022_remove_stockitem_sale_type_stockitem_suggested_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='power_consumption',
            field=models.PositiveIntegerField(default=150, help_text='Consumo medio in Watt della stampante durante la stampa.'),
        ),
    ]
