# Generated by Django 5.2.3 on 2025-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0023_printer_power_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attiva'),
        ),
    ]
