# Generated by Django 5.2.3 on 2025-07-12 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0024_spool_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='last_maintenance_reset',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo Reset Manutenzione'),
        ),
    ]
