# Generated by Django 5.2.3 on 2025-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0025_printer_last_maintenance_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='weight_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Aggiustamento Manuale (g)'),
        ),
    ]
