# Generated by Django 5.2.3 on 2025-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0026_spool_weight_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Manodopera'),
        ),
    ]
