# Generated by Django 5.2.3 on 2025-12-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0027_stockitem_labor_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Spesa', 'verbose_name_plural': 'Spese'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Categoria Spesa'},
        ),
        migrations.AlterModelOptions(
            name='filament',
            options={'verbose_name': 'Filamento', 'verbose_name_plural': 'Filamenti'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-log_date'], 'verbose_name': 'Log Manutenzione'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Metodo di Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='printfile',
            options={'verbose_name': 'File di Stampa', 'verbose_name_plural': 'File di Stampa'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
        migrations.AlterModelOptions(
            name='spool',
            options={'verbose_name': 'Bobina', 'verbose_name_plural': 'Bobine'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Oggetto Magazzino', 'verbose_name_plural': 'Magazzino'},
        ),
        migrations.RemoveField(
            model_name='printfile',
            name='spools',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_quantity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='produced_quantity',
        ),
        migrations.AddField(
            model_name='filament',
            name='density',
            field=models.DecimalField(decimal_places=2, default=1.24, max_digits=5, verbose_name='Densità (g/cm3)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.expensecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='bed_temp',
            field=models.PositiveIntegerField(default=60, verbose_name='Temp. Piatto (°C)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codice Colore (es. Matte Black)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Colore Esadecimale'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_name',
            field=models.CharField(max_length=50, verbose_name='Nome Colore'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='material',
            field=models.CharField(max_length=50, verbose_name='Materiale (es. PLA, PETG)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='nozzle_temp',
            field=models.PositiveIntegerField(default=200, verbose_name='Temp. Ugello (°C)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='volumetric_speed',
            field=models.PositiveIntegerField(default=12, verbose_name='Velocità Volumetrica Max (mm³/s)'),
        ),
        migrations.AlterField(
            model_name='filamentusage',
            name='grams_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Intervento'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Intervento Eseguito'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='app_3dmage_management.printer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Metodo (es. PayPal, Contanti)'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Piatto (es. PEI, Cool Plate)'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantità Effettiva (se multipli)'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome File (es. base_v2.gcode)'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.plate', verbose_name='Piatto'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='print_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo di Stampa (s)'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_files', to='app_3dmage_management.printer', verbose_name='Stampante'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantità Prodotta per Stampa'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='status',
            field=models.CharField(choices=[('TODO', 'In Coda'), ('PRINTING', 'In Stampa'), ('DONE', 'Stampato'), ('FAILED', 'Fallito')], default='TODO', max_length=10, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completato il'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Personalizzato (es. 24001)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Bassa'), ('NORMAL', 'Normale'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Priorità'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantità Oggetti'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('QUOTE', 'Preventivo'), ('TODO', 'Da Fare'), ('IN_PROGRESS', 'In Corso'), ('DONE', 'Completato'), ('POST', 'Post Produzione')], default='TODO', max_length=15, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Bobina (€)'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='identifier',
            field=models.CharField(blank=True, max_length=10, verbose_name='Identificativo (es. A, B, C)'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='initial_weight_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Iniziale (g)'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='purchase_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Acquisto'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='weight_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Correzione Peso Manuale (g)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Oggetto'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note Vendita'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.paymentmethod', verbose_name='Pagato con'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='app_3dmage_management.project'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo Vendita (Cad.)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sold_to',
            field=models.CharField(blank=True, max_length=200, verbose_name='Venduto a'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Magazzino'), ('SOLD', 'Venduto')], default='IN_STOCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo Suggerito (Cad.)'),
        ),
    ]
