# Generated by Django 5.2.3 on 2025-12-13 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0028_alter_expense_options_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Spesa', 'verbose_name_plural': 'Spese'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Categoria Spesa', 'verbose_name_plural': 'Categorie Spesa'},
        ),
        migrations.AlterModelOptions(
            name='filament',
            options={'ordering': ['material', 'brand', 'color_code'], 'verbose_name': 'Filamento', 'verbose_name_plural': 'Filamenti'},
        ),
        migrations.AlterModelOptions(
            name='maintenancelog',
            options={'ordering': ['-log_date'], 'verbose_name': 'Log Manutenzione', 'verbose_name_plural': 'Log Manutenzioni'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Metodo di Pagamento', 'verbose_name_plural': 'Metodi di Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='printfile',
            options={'ordering': ['queue_position'], 'verbose_name': 'File di Stampa', 'verbose_name_plural': 'File di Stampa'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ['purchase_date', 'identifier'], 'verbose_name': 'Bobina', 'verbose_name_plural': 'Bobine'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oggetto a Magazzino', 'verbose_name_plural': 'Oggetti a Magazzino'},
        ),
        migrations.RemoveField(
            model_name='filament',
            name='density',
        ),
        migrations.AddField(
            model_name='printfile',
            name='spools',
            field=models.ManyToManyField(related_name='print_files_usage', through='app_3dmage_management.FilamentUsage', to='app_3dmage_management.spool'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.expensecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='bed_temp',
            field=models.PositiveIntegerField(default=60, verbose_name='Temperatura Piatto (°C)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_code',
            field=models.CharField(max_length=3, verbose_name='Codice Colore'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Codice Colore HEX'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome Colore'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='material',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('ASA', 'ASA')], max_length=10, verbose_name='Materiale'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='nozzle_temp',
            field=models.PositiveIntegerField(default=215, verbose_name='Temperatura Ugello (°C)'),
        ),
        migrations.AlterField(
            model_name='filament',
            name='volumetric_speed',
            field=models.PositiveIntegerField(default=15, verbose_name='Velocità Volumetrica (mm³/s)'),
        ),
        migrations.AlterField(
            model_name='filamentusage',
            name='grams_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Grammi Usati'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Ricambi (€)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrizione Intervento'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note Aggiuntive'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='app_3dmage_management.printer', verbose_name='Stampante'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Letta'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Attuale'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome Metodo'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Piatto'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Oggetti Stampati Effettivi'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Creazione'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome G-Code'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.plate', verbose_name='Piatto Usato'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='print_time_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo di Stampa (secondi)'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_files', to='app_3dmage_management.printer', verbose_name='Stampante Usata'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Oggetti per Stampa'),
        ),
        migrations.AlterField(
            model_name='printfile',
            name='status',
            field=models.CharField(choices=[('TODO', 'Da Stampare'), ('PRINTING', 'In Stampa'), ('DONE', 'Stampato'), ('FAILED', 'Fallito')], default='TODO', max_length=10, verbose_name='Status Stampa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Completamento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creato il'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ID Personalizzato'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Annotazioni'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgente'), ('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Bassa')], default='MEDIUM', max_length=10, verbose_name='Priorità'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantità oggetti ordine'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('QUOTE', 'Preventivo'), ('TODO', 'Da Stampare'), ('POST', 'Post-Produzione'), ('DONE', 'Completato')], default='QUOTE', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo (€)'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='identifier',
            field=models.CharField(blank=True, max_length=2, verbose_name='Identificatore'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='initial_weight_g',
            field=models.PositiveIntegerField(default=1000, verbose_name='Peso Iniziale (g)'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Link Acquisto'),
        ),
        migrations.AlterField(
            model_name='spool',
            name='weight_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Aggiustamento Manuale (g)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Aggiunto il'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Personalizzato'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note sulla vendita'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.paymentmethod', verbose_name='Metodo di Pagamento'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.project', verbose_name='Progetto Originale'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo di Vendita'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sold_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Venduto a (o rimborsato da)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('POST_PROD', 'Post-Produzione'), ('IN_STOCK', 'A Magazzino'), ('CONSIGNMENT', 'Conto Vendita'), ('SOLD', 'Venduto')], default='POST_PROD', max_length=20, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prezzo di Vendita Previsto'),
        ),
    ]
