# Generated by Django 5.2.3 on 2025-12-26 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0030_project_locked_at_project_locked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='WorkOrder',
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ordine di Lavoro', 'verbose_name_plural': 'Ordini di Lavoro'},
        ),
        migrations.RenameField(
            model_name='printfile',
            old_name='project',
            new_name='work_order',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='project',
            new_name='work_order',
        ),
        migrations.AlterField(
            model_name='printfile',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_files', to='app_3dmage_management.workorder', verbose_name='Ordine di Lavoro'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.workorder', verbose_name='Ordine di Lavoro Originale'),
        ),
    ]
