# Generated by Django 5.2.3 on 2025-12-26 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0031_rename_project_workorder_alter_workorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPrintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome File')),
                ('estimated_time_seconds', models.PositiveIntegerField(default=0)),
                ('suggested_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.plate')),
                ('suggested_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.printer')),
            ],
        ),
        migrations.AddField(
            model_name='printfile',
            name='master_print_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='app_3dmage_management.masterprintfile', verbose_name='Template Originale'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Progetto')),
                ('base_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità Base')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='project_previews/', verbose_name='Immagine Anteprima')),
                ('notes', models.TextField(blank=True, verbose_name='Annotazioni Master')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Progetto (Master)',
                'verbose_name_plural': 'Progetti (Master)',
            },
        ),
        migrations.AddField(
            model_name='masterprintfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_print_files', to='app_3dmage_management.project'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='app_3dmage_management.project', verbose_name='Progetto Master'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='project_master_category_idx'),
        ),
    ]
