# Generated by Django 5.2.3 on 2025-12-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0032_masterprintfile_printfile_master_print_file_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFilamentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Grammi Stimati')),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_3dmage_management.filament', verbose_name='Filamento Consigliato')),
                ('master_print_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filament_usages', to='app_3dmage_management.masterprintfile')),
            ],
        ),
    ]
