# Generated by Django 5.2.3 on 2026-01-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0034_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprintfile',
            name='suggested_plate',
        ),
        migrations.RemoveField(
            model_name='masterprintfile',
            name='suggested_printer',
        ),
        migrations.AddField(
            model_name='masterprintfile',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.plate', verbose_name='Piatto'),
        ),
        migrations.AddField(
            model_name='masterprintfile',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.printer', verbose_name='Stampante'),
        ),
        migrations.AddField(
            model_name='masterprintfile',
            name='produced_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Oggetti per Stampa'),
        ),
        migrations.CreateModel(
            name='ProjectPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Parte')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordine')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='app_3dmage_management.project', verbose_name='Progetto Master')),
            ],
            options={
                'verbose_name': 'Parte Progetto',
                'verbose_name_plural': 'Parti Progetto',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='masterprintfile',
            name='project_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_print_files', to='app_3dmage_management.projectpart', verbose_name='Parte'),
        ),
    ]
