# Generated by Django 5.2.3 on 2026-01-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0035_remove_masterprintfile_suggested_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tag Stampante (es. MK, A1)'),
        ),
    ]
