# Generated by Django 5.2.3 on 2026-01-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0036_printer_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Output')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità Base')),
                ('code_suffix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Suffisso Codice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='app_3dmage_management.project', verbose_name='Progetto Master')),
            ],
            options={
                'verbose_name': 'Output Progetto',
                'verbose_name_plural': 'Output Progetti',
            },
        ),
    ]
