# Generated by Django 4.2.27 on 2026-01-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0037_projectoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprintfile',
            name='project_parts',
            field=models.ManyToManyField(blank=True, related_name='master_print_files', to='app_3dmage_management.projectpart', verbose_name='Parti'),
        ),
        migrations.AlterField(
            model_name='masterprintfile',
            name='project_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_print_files_old', to='app_3dmage_management.projectpart', verbose_name='Parte (OLD)'),
        ),
    ]
