# Generated by Django 4.2.27 on 2026-01-10 20:17

from django.db import migrations


def migrate_parts(apps, schema_editor):
    MasterPrintFile = apps.get_model('app_3dmage_management', 'MasterPrintFile')
    for mpf in MasterPrintFile.objects.all():
        if mpf.project_part:
            mpf.project_parts.add(mpf.project_part)

class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0038_masterprintfile_project_parts_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_parts),
    ]
