# Generated by Django 4.2.27 on 2026-01-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0039_auto_20260110_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprintfile',
            name='project_part',
        ),
    ]
