# Generated by Django 4.2.27 on 2026-01-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0040_remove_masterprintfile_project_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='project_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_files', to='app_3dmage_management.projectpart', verbose_name='Parte'),
        ),
    ]
