# Generated by Django 4.2.27 on 2026-01-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0041_printfile_project_part'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_master_category_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensioni'),
        ),
        migrations.AddField(
            model_name='project',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo di Vendita Suggerito'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.category', verbose_name='Categoria'),
        ),
    ]
