# Generated by Django 4.2.27 on 2026-04-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0042_remove_project_project_master_category_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_master_category_idx',
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Consegna Prevista'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='project',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.category', verbose_name='Categoria'),
                ),
            ],
            database_operations=[],
        ),
    ]
