# Generated by Django 4.2.27 on 2026-01-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0042_remove_project_project_master_category_idx_and_more'),
    ]

    operations = [
    ]
