# Generated by Django 4.2.27 on 2026-06-13 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0043_remove_project_project_master_category_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome Materia Prima')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materie Prime',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantità Acquistata')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Totale (€)')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Acquisto')),
                ('purchase_link', models.URLField(blank=True, max_length=512, null=True, verbose_name='Link Acquisto')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_purchase', to='app_3dmage_management.expense')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_3dmage_management.paymentmethod', verbose_name='Pagato con')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app_3dmage_management.rawmaterial', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Acquisto Materia Prima',
                'verbose_name_plural': 'Acquisti Materie Prime',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità Utilizzata')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_usages', to='app_3dmage_management.rawmaterial', verbose_name='Materia Prima')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='app_3dmage_management.workorder', verbose_name='Ordine di Lavoro')),
            ],
            options={
                'verbose_name': 'Materia Prima Ordine',
                'verbose_name_plural': 'Materie Prime Ordine',
                'unique_together': {('work_order', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità Utilizzata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='app_3dmage_management.project', verbose_name='Progetto Master')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usages', to='app_3dmage_management.rawmaterial', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Materia Prima Progetto',
                'verbose_name_plural': 'Materie Prime Progetto',
                'unique_together': {('project', 'raw_material')},
            },
        ),
    ]
