# Generated by Django 4.2.27 on 2026-01-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0043_remove_project_project_master_category_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_master_category_idx',
        ),
    ]
