# Generated by Django 4.2.27 on 2026-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3dmage_management', '0044_remove_project_project_master_category_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensioni'),
        ),
        migrations.AddField(
            model_name='project',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prezzo di Vendita Suggerito'),
        ),
    ]
